import {
  FULL_WIDTH,
  ThemeDefinition,
  baseBorderWidths,
  baseComponentSizes,
  baseComponentTokens,
  baseRadii,
  baseIconSizes,
  baseLayout,
  baseLetterSpacing,
  baseLineHeights,
  baseOpacity,
  baseSpacing,
  baseTypography,
} from "./types";

const colors = {
  background: "#1a3d2e",
  surface: "#2d5a47",
  overlay: "#3d6b58",
  surfaceVariant: "#4a7a65",
  surfaceSubdued: "#2d5a47",
  surfaceMuted: "#1f4535",
  primary: "#4a9d7a",
  onPrimary: "#ffffff",
  muted: "#5a7a6a",
  textPrimary: "#e8f5e9",
  textSecondary: "#c8e6c9",
  textMuted: "#81c784",
  border: "#3d6b58",
  accent: "#66bb6a",
  accentOnPrimary: "#ffffff",
  success: "#4caf50",
  danger: "#f44336",
  info: "#2196f3",
  logoFill: "#e8f5e9",
  logoPrimaryColor: "#66bb6a",
  logoSecondaryColor: "#4a9d7a",
  logoTertiaryColor: "#2d5a47",
  imageBackgroundColor: "#2d5a47",
} as const;

export const forrestTheme: ThemeDefinition = {
  label: "Forrest",
  description: "Earthy lush greens inspired by deep forests and natural growth.",
  tokens: {
    colors,
    spacing: baseSpacing,
    padding: {
      screen: 12,
      section: 16,
      card: 12,
      compact: 6,
    },
    radii: {
      sm: 8,
      md: 12,
      lg: 20,
      round: baseRadii.round,
      radiusControl: 8,
      radiusCard: 12,
      radiusSurface: 20,
      radiusPill: baseRadii.round,
    },
    typography: baseTypography,
    fontFamilies: {
      display: "Isenheim-Regulier, serif",
      regular: "SpaceGrotesk-Regular, sans-serif",
      light: "SpaceGrotesk-Light, sans-serif",
      lightItalic: "SpaceGrotesk-Regular, sans-serif",
      medium: "SpaceGrotesk-Medium, sans-serif",
      semiBold: "SpaceGrotesk-Medium, sans-serif",
      bold: "SpaceGrotesk-Bold, sans-serif",
    },
    layout: baseLayout,
    shadows: {
      card: {
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 3,
      },
      floating: {
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 12,
        elevation: 6,
      },
    },
    borderWidths: baseBorderWidths,
    lineHeights: baseLineHeights,
    letterSpacing: baseLetterSpacing,
    opacity: baseOpacity,
    iconSizes: baseIconSizes,
    widths: { full: FULL_WIDTH },
    componentSizes: baseComponentSizes,
    components: {
      ...baseComponentTokens,
      tabBar: {
        containerBackground: colors.background,
        slotBackground: colors.background,
        list: {
          paddingHorizontal: baseSpacing.xxs,
          paddingVertical: baseSpacing.xxs,
          marginHorizontal: baseSpacing.xs,
          marginBottom: baseSpacing.xxl,
          borderRadius: 12,
          backgroundColor: colors.surface,
          borderWidth: 1,
          borderColor: colors.border,
          shadow: null,
        },
        trigger: {
          paddingHorizontal: baseSpacing.sm,
          paddingVertical: baseSpacing.xs,
          borderRadius: 12,
          minHeight: 32,
          shape: "pill",
          inactiveBackgroundColor: colors.overlay,
          activeBackgroundColor: colors.accent,
        },
        label: {
          show: true,
          color: colors.textPrimary,
          activeColor: colors.accentOnPrimary,
          uppercase: false,
          letterSpacing: baseLetterSpacing.normal,
          marginLeftWithIcon: baseSpacing.xxs,
        },
      },
    },
  },
  assets: {
    logo: "/assets/images/logo.svg",
  },
};
