import {
  FULL_WIDTH,
  ThemeDefinition,
  baseBorderWidths,
  baseComponentSizes,
  baseComponentTokens,
  baseRadii,
  baseIconSizes,
  baseLayout,
  baseLetterSpacing,
  baseLineHeights,
  baseOpacity,
  baseSpacing,
  baseTypography,
} from "./types";

const colors = {
  background: "#fff8e1",
  surface: "#ffe0b2",
  overlay: "#fff3e0",
  surfaceVariant: "#ffcc80",
  surfaceSubdued: "#ffe0b2",
  surfaceMuted: "#ffcc80",
  primary: "#ff8f00",
  onPrimary: "#ffffff",
  muted: "#d4a574",
  textPrimary: "#5d4037",
  textSecondary: "#8d6e63",
  textMuted: "#a1887f",
  border: "#ffb74d",
  accent: "#ffa726",
  accentOnPrimary: "#ffffff",
  success: "#66bb6a",
  danger: "#ef5350",
  info: "#42a5f5",
  logoFill: "#5d4037",
  logoPrimaryColor: "#ffa726",
  logoSecondaryColor: "#ff8f00",
  logoTertiaryColor: "#ffe0b2",
  imageBackgroundColor: "#ffe0b2",
} as const;

export const lazySundayMorningTheme: ThemeDefinition = {
  label: "Lazy Sunday Morning",
  description: "Yolk yellow, orange juice, pancakes, and coffee - the feeling of a relaxed Sunday morning.",
  tokens: {
    colors,
    spacing: baseSpacing,
    padding: {
      screen: 16,
      section: 20,
      card: 16,
      compact: 8,
    },
    radii: {
      sm: 12,
      md: 16,
      lg: 24,
      round: baseRadii.round,
    },
    typography: baseTypography,
    fontFamilies: {
      display: "Career, serif",
      regular: "HostGrotesk-Regular, sans-serif",
      light: "HostGrotesk-Light, sans-serif",
      lightItalic: "HostGrotesk-LightItalic, sans-serif",
      medium: "HostGrotesk-Medium, sans-serif",
      semiBold: "HostGrotesk-SemiBold, sans-serif",
      bold: "HostGrotesk-Bold, sans-serif",
    },
    layout: baseLayout,
    shadows: {
      card: {
        shadowColor: "#ff8f00",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 2,
      },
      floating: {
        shadowColor: "#ff8f00",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 4,
      },
    },
    borderWidths: baseBorderWidths,
    lineHeights: baseLineHeights,
    letterSpacing: baseLetterSpacing,
    opacity: baseOpacity,
    iconSizes: baseIconSizes,
    widths: { full: FULL_WIDTH },
    componentSizes: baseComponentSizes,
    components: {
      ...baseComponentTokens,
      tabBar: {
        containerBackground: colors.background,
        slotBackground: colors.background,
        list: {
          paddingHorizontal: baseSpacing.xxs,
          paddingVertical: baseSpacing.xxs,
          marginHorizontal: baseSpacing.xs,
          marginBottom: baseSpacing.xxl,
          borderRadius: 16,
          backgroundColor: colors.surface,
          borderWidth: 1,
          borderColor: colors.border,
          shadow: null,
        },
        trigger: {
          paddingHorizontal: baseSpacing.sm,
          paddingVertical: baseSpacing.xs,
          borderRadius: 16,
          minHeight: 32,
          shape: "pill",
          inactiveBackgroundColor: colors.overlay,
          activeBackgroundColor: colors.accent,
        },
        label: {
          show: true,
          color: colors.textPrimary,
          activeColor: colors.accentOnPrimary,
          uppercase: false,
          letterSpacing: baseLetterSpacing.normal,
          marginLeftWithIcon: baseSpacing.xxs,
        },
      },
    },
  },
  assets: {
    logo: "/assets/images/logo.svg",
  },
};
