import {
  FULL_WIDTH,
  ThemeDefinition,
  baseBorderWidths,
  baseComponentSizes,
  baseComponentTokens,
  baseRadii,
  baseIconSizes,
  baseLayout,
  baseLetterSpacing,
  baseLineHeights,
  baseOpacity,
  baseSpacing,
  baseTypography,
} from "./types";

const colors = {
  background: "#f5f5e6",
  surface: "#f5f5e6",
  overlay: "#d4d4c5",
  surfaceVariant: "#e0e0d1",
  surfaceSubdued: "#f5f5e6",
  surfaceMuted: "#e8e8d9",
  primary: "#1a1a1a",
  onPrimary: "#f5f5e6",
  muted: "#1a1a1a",
  textPrimary: "#1a1a1a",
  textSecondary: "#1a1a1a",
  textMuted: "#1a1a1a",
  border: "#1a1a1a",
  accent: "#1a1a1a",
  accentOnPrimary: "#f5f5e6",
  success: "#1a1a1a",
  danger: "#1a1a1a",
  info: "#1a1a1a",
  logoFill: "#1a1a1a",
  logoPrimaryColor: "#1a1a1a",
  logoSecondaryColor: "#1a1a1a",
  logoTertiaryColor: "#4a4a4a",
  imageBackgroundColor: "#f5f5e6",
} as const;

export const simpleComputerTheme: ThemeDefinition = {
  label: "typewriter",
  description: "Minimal monospace aesthetic with inverted cream and dark gray tones.",
  tokens: {
    colors,
    spacing: baseSpacing,
    padding: {
      screen: 8,
      section: 12,
      card: 8,
      compact: 4,
    },
    radii: {
      sm: 0,
      md: 0,
      lg: 0,
      round: baseRadii.round,
    },
    typography: baseTypography,
    fontFamilies: {
      display: "LTSuperiorMono-Medium, monospace",
      regular: "LTSuperiorMono-Regular, monospace",
      light: "LTSuperiorMono-Regular, monospace",
      lightItalic: "LTSuperiorMono-Regular, monospace",
      medium: "LTSuperiorMono-Medium, monospace",
      semiBold: "LTSuperiorMono-Semibold, monospace",
      bold: "LTSuperiorMono-Bold, monospace",
    },
    layout: baseLayout,
    shadows: {
      card: {
        shadowColor: "#1a1a1a",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
      },
      floating: {
        shadowColor: "#1a1a1a",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
      },
    },
    borderWidths: baseBorderWidths,
    lineHeights: baseLineHeights,
    letterSpacing: baseLetterSpacing,
    opacity: baseOpacity,
    iconSizes: baseIconSizes,
    widths: { full: FULL_WIDTH },
    componentSizes: baseComponentSizes,
    components: {
      ...baseComponentTokens,
      tabBar: {
        containerBackground: colors.background,
        slotBackground: colors.background,
        list: {
          paddingHorizontal: baseSpacing.xxs,
          paddingVertical: baseSpacing.xxs,
          marginHorizontal: baseSpacing.xs,
          marginBottom: baseSpacing.xxl,
          borderRadius: 0,
          backgroundColor: colors.surface,
          borderWidth: 2,
          borderColor: colors.border,
          shadow: null,
        },
        trigger: {
          paddingHorizontal: baseSpacing.sm,
          paddingVertical: baseSpacing.xs,
          borderRadius: 0,
          minHeight: 32,
          shape: "pill",
          inactiveBackgroundColor: colors.overlay,
          activeBackgroundColor: colors.accent,
        },
        label: {
          show: true,
          color: colors.textPrimary,
          activeColor: colors.accentOnPrimary,
          uppercase: false,
          letterSpacing: baseLetterSpacing.tight,
          marginLeftWithIcon: baseSpacing.xxs,
        },
      },
    },
  },
  assets: {
    logo: "/assets/images/logo.svg",
  },
};
